create extension if not exists pgcrypto;

create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    email text unique,
    display_name text,
    avatar_url text,
    preferred_tier text not null default 'free',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.subscriptions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.users(id) on delete cascade,
    provider text not null check (provider in ('app_store', 'stripe', 'admin')),
    provider_customer_id text,
    provider_subscription_id text,
    plan_code text not null,
    status text not null check (status in ('trialing', 'active', 'past_due', 'canceled', 'expired')),
    current_period_start timestamptz,
    current_period_end timestamptz,
    cancel_at_period_end boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.devices (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.users(id) on delete cascade,
    device_name text not null,
    platform text not null check (platform in ('ios', 'ipados', 'macos')),
    app_version text,
    last_seen_at timestamptz,
    push_token text,
    is_revoked boolean not null default false,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.ssh_profiles_metadata (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.users(id) on delete cascade,
    label text not null,
    host text not null,
    port integer not null default 22 check (port > 0 and port < 65536),
    username text not null,
    auth_kind text not null check (auth_kind in ('password', 'key', 'agent', 'certificate')),
    public_key_fingerprint text,
    vault_reference text,
    last_connected_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.snippets (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.users(id) on delete cascade,
    title text not null,
    body text not null,
    shell_kind text not null default 'bash' check (shell_kind in ('bash', 'zsh', 'fish', 'sh', 'powershell')),
    is_favorite boolean not null default false,
    tags text[] not null default '{}',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.ai_usage (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users(id) on delete cascade,
    device_id uuid references public.devices(id) on delete set null,
    feature_code text not null,
    prompt_tokens integer not null default 0,
    completion_tokens integer not null default 0,
    request_count integer not null default 1,
    provider text not null,
    model text,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.server_monitors (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.users(id) on delete cascade,
    ssh_profile_id uuid references public.ssh_profiles_metadata(id) on delete cascade,
    label text not null,
    host text not null,
    cpu_threshold numeric(5,2),
    memory_threshold numeric(5,2),
    disk_threshold numeric(5,2),
    alert_webhook_url text,
    last_snapshot jsonb not null default '{}'::jsonb,
    last_alert_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id) on delete set null,
    device_id uuid references public.devices(id) on delete set null,
    action text not null,
    target_type text not null,
    target_id text,
    ip_address inet,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists subscriptions_user_status_idx on public.subscriptions (user_id, status);
create index if not exists devices_user_last_seen_idx on public.devices (user_id, last_seen_at desc);
create index if not exists ssh_profiles_user_host_idx on public.ssh_profiles_metadata (user_id, host);
create index if not exists snippets_user_updated_idx on public.snippets (user_id, updated_at desc);
create index if not exists ai_usage_user_created_idx on public.ai_usage (user_id, created_at desc);
create index if not exists server_monitors_user_profile_idx on public.server_monitors (user_id, ssh_profile_id);
create index if not exists audit_logs_user_created_idx on public.audit_logs (user_id, created_at desc);

alter table public.users enable row level security;
alter table public.subscriptions enable row level security;
alter table public.devices enable row level security;
alter table public.ssh_profiles_metadata enable row level security;
alter table public.snippets enable row level security;
alter table public.ai_usage enable row level security;
alter table public.server_monitors enable row level security;
alter table public.audit_logs enable row level security;

create policy "users_select_own" on public.users
    for select using (auth.uid() = id);

create policy "users_update_own" on public.users
    for update using (auth.uid() = id);

create policy "subscriptions_select_own" on public.subscriptions
    for select using (auth.uid() = user_id);

create policy "devices_manage_own" on public.devices
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "ssh_profiles_manage_own" on public.ssh_profiles_metadata
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "snippets_manage_own" on public.snippets
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "ai_usage_insert_own" on public.ai_usage
    for insert with check (auth.uid() = user_id);

create policy "ai_usage_select_own" on public.ai_usage
    for select using (auth.uid() = user_id);

create policy "server_monitors_manage_own" on public.server_monitors
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "audit_logs_select_own" on public.audit_logs
    for select using (auth.uid() = user_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at
before update on public.users
for each row execute function public.touch_updated_at();

drop trigger if exists subscriptions_touch_updated_at on public.subscriptions;
create trigger subscriptions_touch_updated_at
before update on public.subscriptions
for each row execute function public.touch_updated_at();

drop trigger if exists ssh_profiles_metadata_touch_updated_at on public.ssh_profiles_metadata;
create trigger ssh_profiles_metadata_touch_updated_at
before update on public.ssh_profiles_metadata
for each row execute function public.touch_updated_at();

drop trigger if exists snippets_touch_updated_at on public.snippets;
create trigger snippets_touch_updated_at
before update on public.snippets
for each row execute function public.touch_updated_at();

drop trigger if exists server_monitors_touch_updated_at on public.server_monitors;
create trigger server_monitors_touch_updated_at
before update on public.server_monitors
for each row execute function public.touch_updated_at();
